# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3'
services:
  dockovpn:
    image: etzion/openvpn
    container_name: vpn
    cap_add:
        - NET_ADMIN
    ports:
        - 1194:1194/udp
    expose:
        - 8080
    environment:
        HOST_ADDR: ${HOST_ADDR} 
    volumes:
        - ./openvpn_conf:/etc/openvpn
        - ./openvpn_data:/opt/Dockovpn_data
    restart: always

nginx:
    image: nginx
    ports:
        - 8090:80
    volumes:
        - ./nginx/htpasswd:/etc/nginx/htpasswd
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
